# Azure DevOps Pipeline for .NET App Infrastructure Deployment

trigger: none

paths:
  include:
  - bicep/*
  - parameters/*
  - pipelines/*

variables:
  # Azure Service Connection name (update this with your actual service connection name)
  azureServiceConnection: 'ReqSer-app-infra-Dev'
  # Subscription ID
  subscriptionId: '$(subscriptionId)'
  # Resource Group Name
  resourceGroupName: 'rg-dotnet-app-$(Build.BuildId)'
  # Location
  location: 'East US'
  # Web App Name
  webAppName: 'webapp-dotnet-$(Build.BuildId)'
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  displayName: 'Validate Bicep Templates'
  jobs:
  - job: ValidateBicep
    displayName: 'Validate Bicep'
    steps:
    - task: AzureCLI@2
      displayName: 'Install Bicep CLI'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          az bicep version
    
    - task: AzureCLI@2
      displayName: 'Validate Bicep Template'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub validate \
            --location "$(location)" \
            --template-file bicep/deploy.bicep \
            --parameters resourceGroupName="$(resourceGroupName)" \
                        location="$(location)" \
                        webAppName="$(webAppName)"

- stage: Deploy
  displayName: 'Deploy Infrastructure'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy to Azure'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep Template'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub create \
                  --location "$(location)" \
                  --template-file bicep/deploy.bicep \
                  --parameters resourceGroupName="$(resourceGroupName)" \
                              location="$(location)" \
                              webAppName="$(webAppName)" \
                  --name "infrastructure-deployment-$(Build.BuildId)"
          
          - task: AzureCLI@2
            displayName: 'Get Deployment Outputs'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Get the web app URL from deployment outputs
                webAppUrl=$(az deployment sub show \
                  --name "infrastructure-deployment-$(Build.BuildId)" \
                  --query properties.outputs.webAppUrl.value \
                  --output tsv)
                
                echo "Web App URL: $webAppUrl"
                echo "##vso[task.setvariable variable=webAppUrl;isOutput=true]$webAppUrl"